/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Kronox
 * Created: 20-lug-2017
 */
--DB username: Kronox password:Kronox1993

CREATE TABLE usertype (
    id_usertype INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomeusertype VARCHAR(128)
);

CREATE TABLE postType (
    id_postType INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipologia VARCHAR(128)
);

CREATE TABLE utenti_registrati (
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nome VARCHAR(128),
    Cognome VARCHAR(128),
    ImmageUrl VARCHAR(128),
    Presentazione VARCHAR (256),
    DataN VARCHAR(20),
    Password VARCHAR(128),
    userType INTEGER,
    FOREIGN KEY (userType) REFERENCES userType(id_userType)
);

CREATE TABLE Posts (
    Id_post INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user INTEGER,
    FOREIGN KEY (user) REFERENCES utenti_registrati(Id) ON DELETE CASCADE,
    Frase VARCHAR(256),
    postType INTEGER,
    idUserBacheca INTEGER,
    FOREIGN KEY (postType) REFERENCES postType(id_postType),
    FOREIGN KEY (idUserBacheca) REFERENCES utenti_registrati(Id) ON DELETE CASCADE,
    Immagine VARCHAR(256)
);

CREATE TABLE Gruppi (
    id_Gruppi INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomeGruppo VARCHAR(256),
    IdUserProprietario INTEGER,
    FOREIGN KEY (IdUserProprietario) REFERENCES utenti_registrati(Id) ON DELETE CASCADE
);

INSERT INTO userType (id_userType, nomeuserType)
VALUES (default, 'Admin');


INSERT INTO userType (id_userType, nomeuserType)
VALUES (default, 'User');

INSERT INTO utenti_registrati (Id, Nome, Cognome, ImmageUrl, Presentazione, DataN, Password, UserType)
VALUES (default, 'Admin', 'Istrator', '', 'Admin of the site','07-JAN-93', 'Kronox1993', 1);

INSERT INTO utentiRegistrati (personalID, nomeUtente, cognomeUtente, url, biografia, dataNascita, password, UtenteType)
VALUES (default, 'Shinji', 'Ikari', 'img/Shinji.jpg', 'Pilota dello 01','06-JUN-01', 'Papa', 2);

INSERT INTO utentiRegistrati (personalID, nomeUtente, cognomeUtente, url, biografia, dataNascita, password, UtenteType)
VALUES (default, 'Rei', 'Ayanami', 'img/Rei.jpg', 'Pilota dello 00','10-FEB-01', 'Ikari', 2);

INSERT INTO utentiRegistrati (personalID, nomeUtente, cognomeUtente, url, biografia, dataNascita, password, UtenteType)
VALUES (default, 'Asuka soryu', 'Langley', 'img/Asuka.jpg', 'Pilota dello 02','04-DEC-01', 'Mamma', 2);

INSERT INTO postType (id_postType, tipologia)
VALUES (default, 'post_text');

INSERT INTO postType (id_postType, tipologia)
VALUES (default, 'post_immage');

INSERT INTO Posts (id_post, user, Frase, postType , idUserBacheca, Immagine)
VALUES (default,
         2,
         'Se anche penso che dovessi morire per qualche disgrazia, non penso che me ne importerebbe granché. Almeno così ho scritto in un tema a scuola... con il solo risultato di aver fatto arrabbiare il professore.', 
        1,
         2,
         '');

INSERT INTO Posts (id_post, user, Frase, postType , idUserBacheca, Immagine)
VALUES (default,
         3,
         '', 
        2, 
        3,
         'img/Ayanami.jpg');

INSERT INTO Posts (id_post, utente, content, postType , idUtenteBacheca, allegato)
VALUES (default,
         4, 
        'Ich bin S. Asuka Langley, Pilot der EVA Unit 02, und das ist meine EVA!', 
        1, 
        4,
         'Klicken Sie hier um <a href="Eva_02.jpg" target="_blank">EVA 02</a> zu sehen.');
